services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_labs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123

volumes:
  mongo_data:
